backend:
  image:
    tag: "13"

frontend:
  image:
    tag: "7"

database:
  image:
    tag: "7.0"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

